import { v4 as uuidv4 } from 'uuid';

import { db } from './index';
import {
  cart,
  categories,
  couriers,
  deliveryAddresses,
  menuItems,
  orders,
  orderStatuses,
  paymentMethods,
  restaurants,
  users,
} from './schema';

async function seed() {
  console.log('🌱 Заполнение базы данных...');
  await db.delete(orders); // Зависит от cart, users, deliveryAddresses и др.
  await db.delete(cart); // Зависит от menuItems
  await db.delete(menuItems); // Зависит от categories и restaurants
  await db.delete(categories); // Зависит от restaurants
  await db.delete(deliveryAddresses); // Зависит от users
  await db.delete(paymentMethods); // Зависит от users
  await db.delete(couriers); // Используется в orders
  await db.delete(orderStatuses); // Используется в orders
  await db.delete(restaurants); // Родитель для categories/menuItems
  await db.delete(users); // Базовая таблица (после всех зависимостей)

  const restaurantData = [
    {
      id: uuidv4(),
      name: 'Трапеза Ярополка',
      description: 'Традиционная кухня',
      rating: 5,
      deliveryTime: '30-40 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Славянская',
      averagePrice: 1500,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283078/restaurants/ltnv8fxbtrigq7ktnuih.png',
    },
    {
      id: uuidv4(),
      name: 'Мед и перец',
      description: 'Современные блюда с акцентом на местные продукты',
      rating: 4,
      deliveryTime: '40-50 мин',
      deliveryTimeMinutes: 40,
      cuisineType: 'Европейская',
      averagePrice: 2000,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282992/restaurants/dmksrgucgscskqnyderw.png',
    },
    {
      id: uuidv4(),
      name: '«Славянский пир»',
      description: 'Аутентичные рецепты, блюда для гурманов',
      rating: 3,
      deliveryTime: '25-35 мин',
      deliveryTimeMinutes: 25,
      cuisineType: 'Микс кулинарных традиций',
      averagePrice: 1200,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283037/restaurants/tamoycd2apodlt62izxn.png',
    },
    {
      id: uuidv4(),
      name: 'Берестяной двор',
      description: 'Блюда в старинном стиле, традиционные супы и пироги',
      rating: 4.7,
      deliveryTime: '25-35 мин',
      deliveryTimeMinutes: 25,
      cuisineType: 'Традиционная русская',
      averagePrice: 1000,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282880/restaurants/hijm0ygrxnjw6ext4vtq.png',
    },
    {
      id: uuidv4(),
      name: 'Варган',
      description: 'Специи и ароматы севера и юга',
      rating: 4.2,
      deliveryTime: '20-30 мин',
      deliveryTimeMinutes: 20,
      cuisineType: 'Микс кулинарных традиций',
      averagePrice: 900,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283074/restaurants/xjvtqvzepgn5dy6veyc4.png',
    },
    {
      id: uuidv4(),
      name: 'Булочная у Радмилы',
      description: 'Свежая выпечка, пироги и домашние десерты',
      rating: 3.7,
      deliveryTime: '15-25 мин',
      deliveryTimeMinutes: 15,
      cuisineType: 'Кондитерская',
      averagePrice: 700,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283021/restaurants/nnu4rjijthpod1mnlgr6.png',
    },
    {
      id: uuidv4(),
      name: '«Городской дворик»',
      description: 'Уличная еда и сытные закуски',
      rating: 2.7,
      deliveryTime: '20-30 мин',
      deliveryTimeMinutes: 20,
      cuisineType: 'Стритфуд',
      averagePrice: 1000,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282887/restaurants/immcp3xfblmfemrgkejr.png',
    },
    {
      id: uuidv4(),
      name: 'Лесное застолье',
      description: 'Фермерская кухня, экологически чистые продукты',
      rating: 5,
      deliveryTime: '25-35 мин',
      deliveryTimeMinutes: 25,
      cuisineType: 'Органическая',
      averagePrice: 1950,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282997/restaurants/l5bdozy7yggpmwie0ej3.png',
    },
    {
      id: uuidv4(),
      name: 'Рыбацкая артель',
      description: 'Уникальное сочетание вкусов со всего мира.',
      rating: 4.4,
      deliveryTime: '40-50 мин',
      deliveryTimeMinutes: 40,
      cuisineType: 'Рыбная',
      averagePrice: 900,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282907/restaurants/nqmma33tfli0llg2qczt.png',
    },
    {
      id: uuidv4(),
      name: 'Таверна "Дворик"',
      description: 'Традиционная кухня',
      rating: 3.1,
      deliveryTime: '43-52 мин',
      deliveryTimeMinutes: 43,
      cuisineType: 'Французская',
      averagePrice: 2811,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283045/restaurants/kkdcz3aea64l4utpmcyo.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гастрономия Мартина',
      description: 'Традиционная кухня',
      rating: 3.4,
      deliveryTime: '45-55 мин',
      deliveryTimeMinutes: 45,
      cuisineType: 'Средиземноморская',
      averagePrice: 1943,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282915/restaurants/ikeh9eovzebwboaj6d4x.jpg',
    },
    {
      id: uuidv4(),
      name: 'Таверна у Маяка',
      description: 'Традиционная кухня',
      rating: 4.7,
      deliveryTime: '42-47 мин',
      deliveryTimeMinutes: 42,
      cuisineType: 'Азиатская',
      averagePrice: 1044,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283059/restaurants/yrtr5unupu5oclzcq3vb.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гастрономическая площадь',
      description: 'Современная кухня',
      rating: 2.8,
      deliveryTime: '41-52 мин',
      deliveryTimeMinutes: 41,
      cuisineType: 'Американская',
      averagePrice: 2151,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282921/restaurants/swwbq3sw3x1crtaw9ot2.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Бар "Шеф"',
      description: 'Современная кухня',
      rating: 2.6,
      deliveryTime: '46-49 мин',
      deliveryTimeMinutes: 46,
      cuisineType: 'Средиземноморская',
      averagePrice: 2326,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282953/restaurants/zi3fo94bobqjnpfnv2hy.jpg',
    },
    {
      id: uuidv4(),
      name: 'Грильхаус "Восток"',
      description: 'Современная кухня',
      rating: 2.0,
      deliveryTime: '33-40 мин',
      deliveryTimeMinutes: 33,
      cuisineType: 'Азиатская',
      averagePrice: 1342,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282949/restaurants/dfsfyosaw6kdnapwvy2n.jpg',
    },
    {
      id: uuidv4(),
      name: 'Шторм на Неве',
      description: 'Восточная кухня',
      rating: 2.8,
      deliveryTime: '32-52 мин',
      deliveryTimeMinutes: 32,
      cuisineType: 'Средиземноморская',
      averagePrice: 1133,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283027/restaurants/z3cz0emtx7yhg2qhueng.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Берег',
      description: 'Современная кухня',
      rating: 4.5,
      deliveryTime: '39-45 мин',
      deliveryTimeMinutes: 39,
      cuisineType: 'Французская',
      averagePrice: 1800,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282960/restaurants/a20a3kbag3l4qhey8ogn.jpg',
    },
    {
      id: uuidv4(),
      name: 'Шторм в Балтике',
      description: 'Семейное кафе.',
      rating: 1.7,
      deliveryTime: '35-60 мин',
      deliveryTimeMinutes: 35,
      cuisineType: 'Американская',
      averagePrice: 1900,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283036/restaurants/sckos7kmjlykwky2w8tp.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Кафе "На Неве"',
      description: 'Современная кухня',
      rating: 3.9,
      deliveryTime: '28-50 мин',
      deliveryTimeMinutes: 50,
      cuisineType: 'Кавказская',
      averagePrice: 2555,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282972/restaurants/xfwzgyoiossojpw2qtkv.jpg',
    },
    {
      id: uuidv4(),
      name: 'Таверна у Бухты',
      description: 'Традиционная кухня',
      rating: 4.1,
      deliveryTime: '30-45 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Русская',
      averagePrice: 1600,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283048/restaurants/mhma9qlo7wzviubhjk3n.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Кафе "Скала"',
      description: 'Современная кухня',
      rating: 4.2,
      deliveryTime: '28-50 мин',
      deliveryTimeMinutes: 28,
      cuisineType: 'Азиатская',
      averagePrice: 1450,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282982/restaurants/rapfzkdfaxtwzqsh3hw3.jpg',
    },
    {
      id: uuidv4(),
      name: 'Шторм на Пляже',
      description: 'Современная кухня',
      rating: 2.9,
      deliveryTime: '40-55 мин',
      deliveryTimeMinutes: 40,
      cuisineType: 'Американская',
      averagePrice: 2100,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283032/restaurants/ktdmbdwjoxcanzmcjxru.jpg',
    },
    {
      id: uuidv4(),
      name: 'Греческая Таверна',
      description: 'Современная кухня',
      rating: 3.3,
      deliveryTime: '22-50 мин',
      deliveryTimeMinutes: 22,
      cuisineType: 'Греческая',
      averagePrice: 2300,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282940/restaurants/myunzvgfgkebjmvbr3dr.jpg',
    },
    {
      id: uuidv4(),
      name: 'Морская Пена',
      description: 'Семейное кафе.',
      rating: 4.3,
      deliveryTime: '45-50 мин',
      deliveryTimeMinutes: 45,
      cuisineType: 'Средиземноморская',
      averagePrice: 1850,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283002/restaurants/zq3wggs3xmkb78g1ttv6.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гастрономия "Челси"',
      description: 'Традиционная кухня',
      rating: 2.7,
      deliveryTime: '50-60 мин',
      deliveryTimeMinutes: 50,
      cuisineType: 'Русская',
      averagePrice: 1450,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282931/restaurants/flasnw17fdh1qqvboikx.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Парк "Зелёный"',
      description: 'Восточная кухня',
      rating: 3.5,
      deliveryTime: '35-50 мин',
      deliveryTimeMinutes: 35,
      cuisineType: 'Русская',
      averagePrice: 2300,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282990/restaurants/rdsv07qtqh6jd0nnty9s.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гастрономический Плавник',
      description: 'Семейное кафе.',
      rating: 4.0,
      deliveryTime: '30-45 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Средиземноморская',
      averagePrice: 2100,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282925/restaurants/hs52fknjstkv3s6qs7bk.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Кафе на Лагуне',
      description: 'Современная кухня',
      rating: 3.9,
      deliveryTime: '30-50 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Французская',
      averagePrice: 2200,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282967/restaurants/p1ayzaholhto82csn4aa.jpg',
    },
    {
      id: uuidv4(),
      name: 'Фестиваль Вкусов',
      description: 'Гастрономический эксперимент с уникальными блюдами',
      rating: 4.8,
      deliveryTime: '35-45 мин',
      deliveryTimeMinutes: 35,
      cuisineType: 'Фьюжн',
      averagePrice: 1800,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282900/restaurants/dlbmt9dyqa53z0ezczat.jpg',
    },
    {
      id: uuidv4(),
      name: 'Бруклинский Вкус',
      description: 'Американская кухня с новыми акцентами',
      rating: 4.2,
      deliveryTime: '30-40 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Американская',
      averagePrice: 1600,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282883/restaurants/xhbx5rpcejejlwk9njtr.jpg',
    },
    {
      id: uuidv4(),
      name: 'Тайский Лотос',
      description: 'Острая и ароматная кухня Таиланда',
      rating: 4.5,
      deliveryTime: '25-35 мин',
      deliveryTimeMinutes: 25,
      cuisineType: 'Тайская',
      averagePrice: 1300,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283072/restaurants/dzauvztdj7sydrter9dj.jpg',
    },
    {
      id: uuidv4(),
      name: 'Пекарня Лавка',
      description: 'Домашний хлеб, пироги и выпечка',
      rating: 3.9,
      deliveryTime: '20-30 мин',
      deliveryTimeMinutes: 20,
      cuisineType: 'Пекарня',
      averagePrice: 500,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283016/restaurants/iukvgjzgfn6jpweqpswy.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Академия',
      description: 'Лучший гриль в городе',
      rating: 4.1,
      deliveryTime: '40-50 мин',
      deliveryTimeMinutes: 40,
      cuisineType: 'Гриль',
      averagePrice: 2200,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282951/restaurants/vadgutshdnf4uvzrod4s.jpg',
    },
    {
      id: uuidv4(),
      name: 'Санкт-Петербургский Пирог',
      description: 'Русская выпечка и традиционные блюда',
      rating: 4.3,
      deliveryTime: '30-40 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Русская',
      averagePrice: 1200,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283023/restaurants/qpkgiqu7hu7xdnuidgj6.jpg',
    },
    {
      id: uuidv4(),
      name: 'Мексиканская Буря',
      description: 'Острые блюда и коктейли по мексиканским рецептам',
      rating: 4.0,
      deliveryTime: '25-35 мин',
      deliveryTimeMinutes: 25,
      cuisineType: 'Мексиканская',
      averagePrice: 1500,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282998/restaurants/jhrffxv8j8sbey8xlnqd.jpg',
    },
    {
      id: uuidv4(),
      name: 'Лавка Кофе',
      description: 'Лучший кофе и десерты с акцентом на классику',
      rating: 4.4,
      deliveryTime: '15-20 мин',
      deliveryTimeMinutes: 15,
      cuisineType: 'Кофейня',
      averagePrice: 700,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282995/restaurants/hvghnafpycz3uko1ljem.jpg',
    },
    {
      id: uuidv4(),
      name: 'Суши Гурмэ',
      description: 'Свежие суши и сашими по классическим рецептам',
      rating: 5.0,
      deliveryTime: '30-40 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Японская',
      averagePrice: 1700,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283038/restaurants/a4f6cl9slay4apmpxlnu.jpg',
    },
    {
      id: uuidv4(),
      name: 'Ресторан "Токио"',
      description: 'Уникальное сочетание традиционной японской и современной кухни',
      rating: 4.6,
      deliveryTime: '20-30 мин',
      deliveryTimeMinutes: 20,
      cuisineType: 'Японская',
      averagePrice: 2100,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283022/restaurants/w1qlvlqfcsh40xv5t6ze.jpg',
    },
    {
      id: uuidv4(),
      name: 'Кулинарная Мастерская',
      description: 'Традиционная кухня с инновационными подходами',
      rating: 4.0,
      deliveryTime: '25-35 мин',
      deliveryTimeMinutes: 25,
      cuisineType: 'Европейская',
      averagePrice: 1500,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282994/restaurants/jwl5jtzbpnq5cnj6os7t.jpg',
    },
    {
      id: uuidv4(),
      name: 'Палитра Вкусов',
      description: 'Блюда со всего мира, от классики до фьюжн',
      rating: 3.9,
      deliveryTime: '35-45 мин',
      deliveryTimeMinutes: 35,
      cuisineType: 'Международная',
      averagePrice: 1600,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283006/restaurants/vzwh4ha6clg0vluactxq.jpg',
    },
    {
      id: uuidv4(),
      name: 'Бельгийский Кафе',
      description: 'Бельгийские вафли и пиво',
      rating: 4.3,
      deliveryTime: '25-30 мин',
      deliveryTimeMinutes: 25,
      cuisineType: 'Бельгийская',
      averagePrice: 1800,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282879/restaurants/mwljy7krlk3dc0uoh0x7.jpg',
    },
    {
      id: uuidv4(),
      name: 'Паназиатская Кухня',
      description: 'Азия на вашем столе, от Японии до Индии',
      rating: 4.7,
      deliveryTime: '40-50 мин',
      deliveryTimeMinutes: 40,
      cuisineType: 'Азиатская',
      averagePrice: 2000,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283007/restaurants/qteysptctonujxxwuzvu.jpg',
    },
    {
      id: uuidv4(),
      name: 'Пивной Пирог',
      description: 'Сытная еда и широкий выбор пива',
      rating: 3.8,
      deliveryTime: '30-40 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Пивной бар',
      averagePrice: 1300,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283020/restaurants/ac2e5j7v8qdjrlcbomrh.jpg',
    },
    {
      id: uuidv4(),
      name: 'Легенды Средиземноморья',
      description: 'Традиционные блюда с юга Европы',
      rating: 4.5,
      deliveryTime: '35-45 мин',
      deliveryTimeMinutes: 35,
      cuisineType: 'Средиземноморская',
      averagePrice: 2200,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282996/restaurants/qzwwqmc8h7c9kxe5ciw6.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Палата',
      description: 'Лучший гриль-бар в городе с атмосферой уюта',
      rating: 4.2,
      deliveryTime: '40-50 мин',
      deliveryTimeMinutes: 40,
      cuisineType: 'Гриль',
      averagePrice: 1800,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282986/restaurants/ommagct3elvio0ridx8t.jpg',
    },
    {
      id: uuidv4(),
      name: 'Мираторг',
      description: 'Стейкхаус с фокусом на мясо высшего качества',
      rating: 4.3,
      deliveryTime: '30-40 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Стейкхаус',
      averagePrice: 2500,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282999/restaurants/cclfxrcylotiqfemgsnt.jpg',
    },
    {
      id: uuidv4(),
      name: 'Техасская Ранчо',
      description: 'Настоящее техасское барбекю и мясные блюда',
      rating: 4.6,
      deliveryTime: '45-55 мин',
      deliveryTimeMinutes: 45,
      cuisineType: 'Американская',
      averagePrice: 2200,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283064/restaurants/gulbqptlifnszyxmmrci.jpg',
    },
    {
      id: uuidv4(),
      name: 'Морской Ветер',
      description: 'Рыбные блюда и морепродукты по особым рецептам',
      rating: 5.0,
      deliveryTime: '25-35 мин',
      deliveryTimeMinutes: 25,
      cuisineType: 'Рыбная',
      averagePrice: 2000,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283004/restaurants/hcnxyr8zuxnh7hqlsar7.jpg',
    },
    {
      id: uuidv4(),
      name: 'Веганский Рай',
      description: 'Кухня для веганов и вегетарианцев, богатая витаминами и вкусами',
      rating: 4.7,
      deliveryTime: '30-40 мин',
      deliveryTimeMinutes: 30,
      cuisineType: 'Веганская',
      averagePrice: 1400,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744283076/restaurants/g1i0ksectamxgjq5heg7.jpg',
    },
    {
      id: uuidv4(),
      name: 'Итальянский Вкус',
      description: 'Традиционная итальянская кухня с акцентом на пасту и пиццу',
      rating: 4.6,
      deliveryTime: '35-45 мин',
      deliveryTimeMinutes: 35,
      cuisineType: 'Итальянская',
      averagePrice: 1800,
      imageUrl:
        'https://res.cloudinary.com/ddv46fj7f/image/upload/v1744282993/restaurants/hsvvlejkpngkh6ws0peb.jpg',
    },
  ];
  await db.insert(restaurants).values(restaurantData);

  const categoryData = [
    {
      id: uuidv4(),
      restaurantId: restaurantData[0].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[0].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[0].id,
      name: 'Салаты и закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[0].id,
      name: 'Выпечка и десерты',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[1].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[1].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[1].id,
      name: 'Супы',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[1].id,
      name: 'Острые закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[2].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[2].id,
      name: 'Супы',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[2].id,
      name: 'Выпечка и сладкое',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[2].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[3].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[3].id,
      name: 'Закуски и соленья',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[3].id,
      name: 'Супы',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[3].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[4].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[4].id,
      name: 'Закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[4].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[4].id,
      name: 'Снеки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[5].id,
      name: 'Выпечка',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[5].id,
      name: 'Завтраки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[5].id,
      name: 'Десерты',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[5].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[6].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[6].id,
      name: 'Закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[6].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[7].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[7].id,
      name: 'Закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[7].id,
      name: 'Супы',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[7].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[8].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[8].id,
      name: 'Закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[8].id,
      name: 'Супы',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[8].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[9].id,
      name: 'Горячее с огня',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[9].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[9].id,
      name: 'Закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[9].id,
      name: 'Десерты',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[10].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[10].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[10].id,
      name: 'Закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[10].id,
      name: 'Десерты',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[11].id,
      name: 'Основные блюда',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[11].id,
      name: 'Закуски',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[11].id,
      name: 'Напитки',
    },
    {
      id: uuidv4(),
      restaurantId: restaurantData[11].id,
      name: 'Десерты',
    },
  ];
  await db.insert(categories).values(categoryData);

  const menuData = [
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[0].id,
      name: 'Жаркое по-княжески',
      description: 'Сочное мясо с овощами, запечённое по древним рецептам.',
      price: 1200,
      imageUrl: '/images/food1.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[0].id,
      name: 'Печёная баранина с пряностями',
      description: 'Нежная баранина с ароматными травами и специями.',
      price: 1400,
      imageUrl: '/images/food2.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[0].id,
      name: 'Курица в медовом соусе',
      description: 'Курица под медово-горчичной глазурью.',
      price: 1100,
      imageUrl: '/images/food3.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[0].id,
      name: 'Тушёная свинина с картошкой',
      description: 'Свинина, тушёная вместе с картофелем и луком.',
      price: 1300,
      imageUrl: '/images/food4.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[0].id,
      name: 'Каша с мясом',
      description: 'Горячая гречневая каша с тушёным мясом.',
      price: 900,
      imageUrl: '/images/food5.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[0].id,
      name: 'Медовуха с травами',
      description: 'Традиционный напиток из меда с душистыми травами.',
      price: 350,
      imageUrl: '/images/drink1.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[0].id,
      name: 'Квас с мятой',
      description: 'Освежающий квас с добавлением мяты.',
      price: 250,
      imageUrl: '/images/drink2.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[0].id,
      name: 'Морс из лесных ягод',
      description: 'Домашний морс из черники, малины и брусники.',
      price: 300,
      imageUrl: '/images/drink3.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[0].id,
      name: 'Яблочный сбитень',
      description: 'Тёплый напиток из яблок и мёда с пряностями.',
      price: 320,
      imageUrl: '/images/drink4.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[0].id,
      name: 'Салат из свежей зелени с яйцом',
      description: 'Лёгкий салат с травами и варёным яйцом.',
      price: 300,
      imageUrl: '/images/salad1.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[0].id,
      name: 'Свекольник с хреном',
      description: 'Холодный свекольный суп с острой ноткой хрена.',
      price: 350,
      imageUrl: '/images/salad2.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[0].id,
      name: 'Квашеная капуста с морковью и укропом',
      description: 'Домашняя квашеная капуста с морковью и укропом.',
      price: 250,
      imageUrl: '/images/salad3.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[0].id,
      name: 'Салат с копчёной рыбой',
      description: 'Салат из копчёной рыбы и свежей зелени.',
      price: 400,
      imageUrl: '/images/salad4.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[0].id,
      name: 'Пирог с ягодами',
      description: 'Тёплый пирог с начинкой из лесных ягод.',
      price: 500,
      imageUrl: '/images/pie1.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[0].id,
      name: 'Лепёшка с луком',
      description: 'Свежая лепёшка, фаршированная луком.',
      price: 300,
      imageUrl: '/images/pie2.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[0].id,
      name: 'Медовые пряники',
      description: 'Пряники из мёда с ароматом корицы и имбиря.',
      price: 200,
      imageUrl: '/images/pie3.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[1].id,
      name: 'Томлёная говядина с перцем',
      description: 'Мясо томится с душистым перцем и специями.',
      price: 1400,
      imageUrl: '/images/food1.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[1].id,
      name: 'Курица в пряной глазури',
      description: 'Курица под сладко-пряной мёдово-имбирной глазурью.',
      price: 1200,
      imageUrl: '/images/food2.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[1].id,
      name: 'Острая уха',
      description: 'Уха с морепродуктами и перцем чили.',
      price: 800,
      imageUrl: '/images/food3.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[1].id,
      name: 'Курица с имбирём и мёдом',
      description: 'Курица, обжаренная с имбирём и мёдом до карамели.',
      price: 1300,
      imageUrl: '/images/food4.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[1].id,
      name: 'Плов с острыми специями',
      description: 'Ароматный плов с перцем чили и барбарисом.',
      price: 900,
      imageUrl: '/images/food5.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[1].id,
      name: 'Пряный чай с корицей',
      description: 'Чай с корицей, кардамоном и мёдом.',
      price: 300,
      imageUrl: '/images/drink1.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[1].id,
      name: 'Настойка на мёде',
      description: 'Крепкая настойка с травами и натуральным мёдом.',
      price: 450,
      imageUrl: '/images/drink2.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[1].id,
      name: 'Яблочный сбитень',
      description: 'Тёплый напиток из яблок, мёда и пряностей.',
      price: 350,
      imageUrl: '/images/drink3.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[1].id,
      name: 'Клюквенный морс с имбирём',
      description: 'Освежающий морс из клюквы с ноткой имбиря.',
      price: 280,
      imageUrl: '/images/drink4.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[1].id,
      name: 'Рассольник с перловкой',
      description: 'Суп с перловкой, солёными огурцами и душистым перцем.',
      price: 650,
      imageUrl: '/images/soup1.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[1].id,
      name: 'Суп-пюре из тыквы',
      description: 'Сливочный суп-пюре с ноткой имбиря и тыквенных семечек.',
      price: 600,
      imageUrl: '/images/soup2.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[1].id,
      name: 'Борщ с чесноком',
      description: 'Классический борщ с чесноком и сметаной.',
      price: 700,
      imageUrl: '/images/soup3.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[1].id,
      name: 'Крем-суп из шампиньонов',
      description: 'Нежный крем-суп с лесными грибами и сливками.',
      price: 720,
      imageUrl: '/images/soup4.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[1].id,
      name: 'Маринованные перцы',
      description: 'Перцы в остром маринаде с чесноком.',
      price: 250,
      imageUrl: '/images/snack1.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[1].id,
      name: 'Солёные огурцы с чесноком',
      description: 'Хрустящие огурцы с чесночным ароматом.',
      price: 200,
      imageUrl: '/images/snack2.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[1].id,
      name: 'Острая капуста',
      description: 'Квашеная капуста с перцем чили.',
      price: 220,
      imageUrl: '/images/snack3.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[2].id,
      name: 'Свинина, запечённая с яблоками',
      description: 'Ароматное мясо, приготовленное по древнему рецепту с кисло-сладкими яблоками.',
      price: 780,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[2].id,
      name: 'Каша гречневая с грибами',
      description: 'Гречка, томлённая в печи с лесными грибами и пряными травами.',
      price: 450,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[2].id,
      name: 'Картофель с салом и чесноком',
      description: 'Румяной жареный картофель, щедро приправленный чесноком и поджаренным салом.',
      price: 390,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[2].id,
      name: 'Телятина по-домашнему',
      description: 'Нежное мясо в сливочном соусе с луком и морковью.',
      price: 690,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[2].id,
      name: 'Щи из кислой капусты',
      description: 'Классический славянский суп на мясном бульоне с томлёной капустой.',
      price: 330,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[2].id,
      name: 'Похлёбка с перловкой',
      description: 'Плотный и сытный суп с крупой, мясом и кореньями.',
      price: 310,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[2].id,
      name: 'Борщ деревенский',
      description: 'Свекольный суп с мясом, сметаной и чесночной гренкой.',
      price: 370,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[2].id,
      name: 'Пышки с маком',
      description: 'Пышные сладкие булочки с маковой начинкой.',
      price: 120,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[2].id,
      name: 'Лепёшка с луком',
      description: 'Ржаная лепёшка с запечённым луком и специями.',
      price: 140,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[2].id,
      name: 'Пирог с капустой и яйцом',
      description: 'Традиционный открытый пирог на дрожжевом тесте.',
      price: 160,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[2].id,
      name: 'Блинчики с творогом',
      description: 'Тонкие блины с нежной начинкой из сладкого творога.',
      price: 180,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[2].id,
      name: 'Пирог с брусникой',
      description: 'Ягодный пирог с кисло-сладким вкусом и хрустящей корочкой.',
      price: 190,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[2].id,
      name: 'Квас хлебный',
      description: 'Домашний квас из ржаного хлеба с лёгкой кислинкой.',
      price: 150,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[2].id,
      name: 'Морс из вишни',
      description: 'Освежающий напиток из лесной вишни.',
      price: 130,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[2].id,
      name: 'Сбитень пряный',
      description: 'Горячий медовый напиток с корицей и гвоздикой.',
      price: 170,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[2].id,
      name: 'Настойка на травах',
      description: 'Крепкий напиток на основе целебных трав по старинному рецепту.',
      price: 210,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[3].id,
      name: 'Утка, тушённая с клюквой',
      description: 'Ароматная утка, медленно томлённая с клюквой и пряностями.',
      price: 780,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[3].id,
      name: 'Картофель, запечённый в печи',
      description: 'Рассыпчатый деревенский картофель с укропом и маслом.',
      price: 320,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[3].id,
      name: 'Перловка с грибами и луком',
      description: 'Постное блюдо с ароматными лесными грибами.',
      price: 370,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[3].id,
      name: 'Рагу из лесного мяса',
      description: 'Мясное рагу из дичи в густом соусе со специями.',
      price: 840,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id, // Закуски и соленья
      restaurantId: restaurantData[3].id,
      name: 'Соленья деревенские',
      description: 'Огурцы, капуста, чеснок — ассорти домашних солений.',
      price: 280,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[3].id,
      name: 'Грибы маринованные',
      description: 'Ассорти лесных грибов в душистом маринаде.',
      price: 340,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[3].id,
      name: 'Ржаные гренки с чесноком',
      description: 'Хрустящие гренки с пряным ароматом.',
      price: 190,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[3].id,
      name: 'Сало с хреном и луком',
      description: 'Нарезка домашнего сала с пряностями.',
      price: 290,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[3].id,
      name: 'Икра кабачковая',
      description: 'Классическая овощная закуска по-домашнему.',
      price: 230,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[3].id,
      name: 'Уха с дымком',
      description: 'На костре, с тремя сортами рыбы и зеленью.',
      price: 510,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[3].id,
      name: 'Похлёбка с репой и фасолью',
      description: 'На наваристом бульоне, с деревенскими овощами.',
      price: 390,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[3].id,
      name: 'Куриный бульон с яйцом и зеленью',
      description: 'Лёгкий, ароматный бульон с отварным яйцом.',
      price: 360,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[3].id,
      name: 'Квас малиновый',
      description: 'Домашний квас с лёгкой ягодной ноткой.',
      price: 160,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[3].id,
      name: 'Травяной отвар с липой и мёдом',
      description: 'Успокаивающий напиток на основе лесных трав.',
      price: 170,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[3].id,
      name: 'Морс черничный',
      description: 'Свежий морс из северной ягоды.',
      price: 150,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[3].id,
      name: 'Настойка на мяте',
      description: 'Домашняя настойка с мятным охлаждающим вкусом.',
      price: 200,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[4].id,
      name: 'Говяжья вырезка на костре',
      description: 'Сочная говядина, запеченная на живом огне.',
      price: 1600,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[4].id,
      name: 'Свинина в кленовом сиропе',
      description: 'Нежная свинина с ароматной глазурью из кленового сиропа.',
      price: 1350,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[4].id,
      name: 'Копчёная курица с травами',
      description: 'Курица, медленно копченная с душистыми травами.',
      price: 1200,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[4].id,
      name: 'Запечённая баранина с розмарином',
      description: 'Баранина, томлённая с пряным розмарином.',
      price: 1700,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[4].id,
      name: 'Колбаски охотничьи',
      description: 'Домашние копчёные колбаски с пряностями.',
      price: 950,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[4].id,
      name: 'Говяжьи рёбра на углях',
      description: 'Рёбра, приготовленные на древесных углях.',
      price: 1450,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[4].id,
      name: 'Шашлык из индейки',
      description: 'Нежный шашлык из маринованной индейки.',
      price: 1100,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[4].id,
      name: 'Светлое пенное',
      description: 'Освежающее светлое крафтовое пиво.',
      price: 400,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[4].id,
      name: 'Тёмное крафтовое пиво',
      description: 'Густое и насыщенное тёмное пиво.',
      price: 450,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[4].id,
      name: 'Квас с солодом',
      description: 'Домашний квас на солоде и травах.',
      price: 300,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[4].id,
      name: 'Копчёные сырные палочки',
      description: 'Сырные палочки, копчённые по старинным рецептам.',
      price: 500,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[4].id,
      name: 'Орехи в мёде',
      description: 'Ароматные орешки, томлённые в лесном мёде.',
      price: 350,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[4].id,
      name: 'Гренки с чесноком',
      description: 'Хрустящие ржаные гренки с чесноком.',
      price: 300,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[4].id,
      name: 'Сушёная рыбка',
      description: 'Традиционная закуска к пиву — вяленая рыбка.',
      price: 600,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[5].id,
      name: 'Пшеничная лепёшка с мёдом',
      description: 'Мягкая пшеничная лепёшка, политая свежим мёдом.',
      price: 160,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[5].id,
      name: 'Ореховый рулет с корицей',
      description: 'Сдобный рулет с грецким орехом и ароматной корицей.',
      price: 190,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[5].id,
      name: 'Сдобная булочка с изюмом',
      description: 'Пышная булочка с изюмом и сахарной пудрой.',
      price: 140,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[5].id,
      name: 'Ячменный пирожок с яблоками',
      description: 'Домашний пирожок из ячменной муки с начинкой из тушёных яблок.',
      price: 150,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[5].id,
      name: 'Каша на молоке с ягодами',
      description: 'Овсяная каша с лесными ягодами и мёдом.',
      price: 180,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[5].id,
      name: 'Омлет с зеленью и сыром',
      description: 'Пышный омлет с домашним сыром и свежей зеленью.',
      price: 200,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[5].id,
      name: 'Гречневая каша с маслом',
      description: 'Рассыпчатая гречневая каша, заправленная деревенским маслом.',
      price: 160,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[5].id,
      name: 'Творожная запеканка',
      description: 'Нежная запеканка с творогом и изюмом.',
      price: 190,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[5].id,
      name: 'Медовик по-деревенски',
      description: 'Многослойный торт с ароматным мёдом.',
      price: 220,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[5].id,
      name: 'Сырники со сметаной',
      description: 'Поджаристые сырники из домашнего творога со сметаной.',
      price: 170,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[5].id,
      name: 'Пирог с вишней',
      description: 'Сочный пирог с вишнёвой начинкой и хрустящей корочкой.',
      price: 190,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[5].id,
      name: 'Мятное печенье',
      description: 'Рассыпчатое печенье с добавлением свежей мяты.',
      price: 130,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[5].id,
      name: 'Молоко из глиняного кувшина',
      description: 'Свежайшее молоко, подаваемое в традиционной посуде.',
      price: 90,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[5].id,
      name: 'Чай с душицей',
      description: 'Травяной чай с добавлением душицы, приятный и успокаивающий.',
      price: 110,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[5].id,
      name: 'Компот из сухофруктов',
      description: 'Сладкий компот из яблок, груш и изюма.',
      price: 120,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[6].id,
      name: 'Жаркое по-домашнему',
      description: 'Картофель с мясом, тушёные в горшочке с овощами.',
      price: 480,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[6].id,
      name: 'Тефтели в томатном соусе',
      description: 'Мясные тефтели, запечённые с ароматным томатным соусом.',
      price: 430,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[6].id,
      name: 'Гречка с грибами и луком',
      description: 'Рассыпчатая гречневая каша с шампиньонами и луком.',
      price: 320,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[6].id,
      name: 'Картофельное пюре с котлетой',
      description: 'Домашняя котлета из фарша с нежным картофельным пюре.',
      price: 390,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[6].id,
      name: 'Салат из свежих овощей',
      description: 'Огурцы, помидоры, зелень с лёгкой заправкой.',
      price: 270,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[6].id,
      name: 'Селёдка с луком и картошкой',
      description: 'Солёная сельдь с отварным картофелем и репчатым луком.',
      price: 350,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[6].id,
      name: 'Маринованные огурцы',
      description: 'Хрустящие домашние огурцы в уксусной заливке.',
      price: 190,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[6].id,
      name: 'Узвар',
      description: 'Компот из сухофруктов по традиционному рецепту.',
      price: 150,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[6].id,
      name: 'Морс из клюквы',
      description: 'Освежающий морс, насыщенный витаминами.',
      price: 170,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[6].id,
      name: 'Чай с облепихой',
      description: 'Горячий чай с облепихой, мёдом и пряностями.',
      price: 200,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[6].id,
      name: 'Домашний лимонад',
      description: 'Лимонад с мятой и цитрусовыми, приготовленный на месте.',
      price: 180,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[7].id,
      name: 'Олений стейк с брусничным соусом',
      description: 'Сочный стейк из оленины с насыщенным брусничным соусом.',
      price: 1650,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[7].id,
      name: 'Жаркое из дичи',
      description: 'Ароматное тушёное мясо дикой птицы и зверя с овощами.',
      price: 1450,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[7].id,
      name: 'Перловка с белыми грибами',
      description: 'Традиционная каша с ароматом леса и грибов.',
      price: 780,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[7].id,
      name: 'Запечённый заяц с розмарином',
      description: 'Мягкое мясо зайца, приготовленное с душистыми травами.',
      price: 1320,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[7].id,
      name: 'Соленья с лесными грибами',
      description: 'Ассорти из домашних солений и маринованных грибов.',
      price: 560,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[7].id,
      name: 'Ржаные гренки с чесноком',
      description: 'Хрустящие гренки с острым ароматом чеснока.',
      price: 350,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[7].id,
      name: 'Паштет из куропатки',
      description: 'Нежный паштет с ягодным соусом и тостами.',
      price: 620,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[7].id,
      name: 'Грибной крем-суп',
      description: 'Насыщенный крем-суп из лесных грибов.',
      price: 590,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[7].id,
      name: 'Щи из квашеной капусты',
      description: 'Кисловатые щи по старинному рецепту.',
      price: 470,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[7].id,
      name: 'Уха из речной рыбы',
      description: 'Лёгкий рыбный суп с зеленью.',
      price: 520,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[7].id,
      name: 'Мёдовый сбитень',
      description: 'Горячий напиток с мёдом и пряностями.',
      price: 290,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[7].id,
      name: 'Морс из черники',
      description: 'Освежающий напиток из лесной ягоды.',
      price: 270,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[7].id,
      name: 'Кисель из лесных ягод',
      description: 'Плотный напиток с насыщенным ягодным вкусом.',
      price: 250,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[7].id,
      name: 'Травяной чай',
      description: 'Чай из лесных трав: мята, чабрец, зверобой.',
      price: 240,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[8].id,
      name: 'Запечённый судак с лимоном',
      description: 'Нежное филе судака, запечённое с ломтиками лимона и тимьяном.',
      price: 1050,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[8].id,
      name: 'Жареный сом с луком',
      description: 'Сом, обжаренный до золотистой корочки с карамелизированным луком.',
      price: 1100,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[8].id,
      name: 'Угорь в сливочном соусе',
      description: 'Нежный угорь под соусом из сливок и белого вина.',
      price: 1350,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[8].id,
      name: 'Филе щуки в панировке',
      description: 'Хрустящее филе щуки в травяной панировке.',
      price: 950,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[8].id,
      name: 'Селёдка с луком и картофелем',
      description: 'Солёная сельдь подаётся с отварным картофелем и маринованным луком.',
      price: 320,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[8].id,
      name: 'Икра щуки с тостами',
      description: 'Домашняя икра щуки подаётся на хрустящих тостах.',
      price: 410,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[8].id,
      name: 'Рыбные котлеты',
      description: 'Сочные котлеты из речной рыбы с зеленью и специями.',
      price: 480,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[8].id,
      name: 'Уха по-царски',
      description: 'Богатый рыбный бульон с несколькими сортами рыбы и овощами.',
      price: 680,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[8].id,
      name: 'Речной рыбный рассольник',
      description: 'Суп на рассоле с рыбой, перловкой и огурцами.',
      price: 620,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[8].id,
      name: 'Крем-суп из лосося',
      description: 'Нежный суп-пюре из лосося со сливками.',
      price: 730,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[8].id,
      name: 'Хреновуха',
      description: 'Острый настой на хрене с ноткой меда.',
      price: 290,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[8].id,
      name: 'Морс клюквенный',
      description: 'Освежающий морс из клюквы с мятой.',
      price: 260,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[8].id,
      name: 'Квас хлебный',
      description: 'Домашний квас на ржаном солоде.',
      price: 230,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[8].id,
      name: 'Травяной настой',
      description: 'Чай из луговых трав с лёгкой горчинкой.',
      price: 200,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[9].id,
      name: 'Гриль-сети с бараниной',
      description: 'Сочные куски баранины, жаренные на открытом огне.',
      price: 1300,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[9].id,
      name: 'Свинное ребро на углях',
      description: 'Тосты свиных ребрышек, запечённые на углях до золотистой корочки.',
      price: 1400,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[9].id,
      name: 'Рыба на мангале',
      description: 'Свежая рыба, запечённая на мангале с лимоном и зеленью.',
      price: 1100,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[9].id,
      name: 'Телячья нога в травах',
      description: 'Мясо телячьей ноги, томлённое в травах.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[9].id,
      name: 'Картошка с укропом',
      description: 'Запечённая картошка с укропом и чесноком.',
      price: 500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[9].id,
      name: 'Медовуха',
      description: 'Сладкий напиток на основе мёда, идеально подойдёт к мясным блюдам.',
      price: 300,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[9].id,
      name: 'Травяной чай',
      description: 'Чай с лечебными травами, прекрасно утоляет жажду.',
      price: 200,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[9].id,
      name: 'Грог с пряностями',
      description: 'Тёплый алкогольный напиток с корицей и другими пряностями.',
      price: 350,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[9].id,
      name: 'Черный чай с лимоном',
      description: 'Чёрный чай с ломтями свежего лимона.',
      price: 150,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[9].id,
      name: 'Квас домашний',
      description: 'Освежающий квас, сваренный по старинному рецепту.',
      price: 250,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[9].id,
      name: 'Греческий салат',
      description: 'Салат с оливками, фетой и свежими овощами.',
      price: 450,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[9].id,
      name: 'Солёные огурцы с хреном',
      description: 'Огурцы, заквашенные с чесноком и хреном.',
      price: 250,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[9].id,
      name: 'Творожная масса с зеленью',
      description: 'Творог, смешанный с зеленью и чесноком.',
      price: 350,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[9].id,
      name: 'Блины с икрой',
      description: 'Тонкие блины с красной икрой.',
      price: 500,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[9].id,
      name: 'Жареные грибы с луком',
      description: 'Обжаренные грибы с луком и специями.',
      price: 400,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[9].id,
      name: 'Пирог с яблоками',
      description: 'Пирог с яблочной начинкой, посыпанный сахаром.',
      price: 350,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[9].id,
      name: 'Блинчики с медом',
      description: 'Маленькие блинчики, политые мёдом.',
      price: 300,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[9].id,
      name: 'Торт с орехами',
      description: 'Торт с орехами и слоёным тестом.',
      price: 400,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[9].id,
      name: 'Кекс с ягодами',
      description: 'Нежный кекс с ягодами и сладкой глазурью.',
      price: 350,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[9].id,
      name: 'Мёд с орехами',
      description: 'Натуральный мёд с орехами.',
      price: 250,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[10].id,
      name: 'Говядина по-строгановски',
      description: 'Нежное мясо, тушёное в сметанном соусе с грибами и луком.',
      price: 1600,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[10].id,
      name: 'Курица в медово-горчичном соусе',
      description: 'Медово-горчичный соус придает курице невероятный вкус.',
      price: 1300,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[10].id,
      name: 'Свинина по-французски',
      description: 'Мясо свинины, запечённое с сыром, луком и картошкой.',
      price: 1400,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[10].id,
      name: 'Филе индейки с лимоном',
      description: 'Филе индейки, приправленное лимоном и специями, запечённое в духовке.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[10].id,
      name: 'Гриль-самбар с овощами',
      description: 'Овощи, жаренные на гриле с особым самбаром.',
      price: 1200,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[10].id,
      name: 'Грог',
      description: 'Тёплый алкогольный напиток с пряностями.',
      price: 350,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[10].id,
      name: 'Вишневый пунш',
      description: 'Освежающий алкогольный напиток с вишней.',
      price: 400,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[10].id,
      name: 'Медовуха',
      description: 'Традиционный напиток на основе мёда.',
      price: 300,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[10].id,
      name: 'Травяной чай',
      description: 'Чай с полезными травами.',
      price: 200,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[10].id,
      name: 'Черный кофе',
      description: 'Сильный чёрный кофе для бодрости.',
      price: 150,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[10].id,
      name: 'Греческий салат',
      description: 'Салат с оливками, фетой, помидорами и огурцами.',
      price: 500,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[10].id,
      name: 'Капрезе',
      description: 'Салат из помидоров, моцареллы и базилика.',
      price: 450,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[10].id,
      name: 'Цезарь с курицей',
      description: 'Листья салата, куриное филе, соус Цезарь и пармезан.',
      price: 600,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[10].id,
      name: 'Тартар из лосося',
      description: 'Свежий лосось с авокадо и специями.',
      price: 700,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[10].id,
      name: 'Салат с авокадо и креветками',
      description: 'Салат с авокадо, креветками и зелёными листьями.',
      price: 750,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[10].id,
      name: 'Шоколадный торт',
      description: 'Нежный шоколадный торт с орехами.',
      price: 400,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[10].id,
      name: 'Тирамису',
      description: 'Итальянский десерт с маскарпоне и кофе.',
      price: 450,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[10].id,
      name: 'Пирог с ягодами',
      description: 'Сладкий пирог с ягодами в хрустящей корочке.',
      price: 350,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[10].id,
      name: 'Медовик',
      description: 'Пирог с медом и орехами.',
      price: 300,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[10].id,
      name: 'Чизкейк',
      description: 'Творожный десерт с фруктовой начинкой.',
      price: 500,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[11].id,
      name: 'Свинина на вертеле',
      description: 'Сочная свинина, приготовленная на открытом огне.',
      price: 1200,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[11].id,
      name: 'Говядина, тушёная в вине',
      description: 'Мягкая говядина, тушёная в вине с пряными травами.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[11].id,
      name: 'Жареная рыба',
      description: 'Свежая рыба, жаренная до золотистой корочки.',
      price: 900,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[11].id,
      name: 'Запечённая курица с лимоном',
      description: 'Курица, запечённая с лимоном и свежими травами.',
      price: 1000,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[11].id,
      name: 'Печёная картошка с сыром',
      description: 'Запечённый картофель с плавленым сыром и зеленью.',
      price: 500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[11].id,
      name: 'Квас на меду',
      description: 'Освежающий квас с добавлением натурального мёда.',
      price: 200,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[11].id,
      name: 'Ягодный морс',
      description: 'Сладкий морс из лесных ягод.',
      price: 250,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[11].id,
      name: 'Сбитень с гвоздикой',
      description: 'Тёплый напиток на мёде и пряностях.',
      price: 350,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[11].id,
      name: 'Чай с мятой',
      description: 'Чай с ароматной мятой, придающей свежесть.',
      price: 150,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[11].id,
      name: 'Кофе по-деревенски',
      description: 'Крепкий кофе, сваренный по старинному рецепту.',
      price: 300,
      imageUrl: '/images/drink.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[11].id,
      name: 'Маринованные огурцы',
      description: 'Хрустящие огурцы в маринаде с пряностями.',
      price: 150,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[11].id,
      name: 'Сырная нарезка',
      description: 'Ассорти сыров с различными добавками.',
      price: 500,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[11].id,
      name: 'Печёные баклажаны с чесноком',
      description: 'Запечённые баклажаны с чесноком и зеленью.',
      price: 400,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[11].id,
      name: 'Солёная рыба с горчицей',
      description: 'Солёная рыба с пикантным горчичным соусом.',
      price: 600,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[11].id,
      name: 'Жареные грибы с луком',
      description: 'Лесные грибы, обжаренные с луком.',
      price: 350,
      imageUrl: '/images/snack.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[11].id,
      name: 'Мёд с орехами',
      description: 'Натуральный мёд с добавлением орехов.',
      price: 250,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[11].id,
      name: 'Пирог с вишней',
      description: 'Тёплый пирог с вишнями и сахарной пудрой.',
      price: 300,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[11].id,
      name: 'Блины с ягодами',
      description: 'Мягкие блины с ягодной начинкой.',
      price: 350,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[11].id,
      name: 'Запечённые яблоки с медом',
      description: 'Тёплые яблоки, запечённые с медом и корицей.',
      price: 400,
      imageUrl: '/images/dessert.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[11].id,
      name: 'Кекс с орехами',
      description: 'Мягкий кекс с орехами и сахарной корочкой.',
      price: 250,
      imageUrl: '/images/dessert.png',
    },
  ];
  await db.insert(menuItems).values(menuData);

  const userData = [
    {
      id: uuidv4(),
      firstName: 'Иван',
      lastName: 'Иванов',
      accountName: 'ivan123',
      email: 'ivan@example.com',
      passwordHash: 'hashedpassword',
      phone: '79990001122',
    },
  ];
  await db.insert(users).values(userData);

  const addressData = [
    { id: 1, userId: userData[0].id, address: 'Ленина, 10', comment: 'code: 1111' },
  ];
  await db.insert(deliveryAddresses).values(addressData);

  const paymentMethodsData = [
    { id: 1, userId: userData[0].id, type: 'card', details: '1234432143211234' },
  ];
  await db.insert(paymentMethods).values(paymentMethodsData);

  const statusData = [
    { id: 1, name: 'Создан' },
    { id: 2, name: 'В пути' },
    { id: 3, name: 'Доставлен' },
  ];
  await db.insert(orderStatuses).values(statusData);

  const courierData = [{ id: 1, name: 'Сергей', phone: '79991234567' }];
  await db.insert(couriers).values(courierData);

  const cartData = [
    {
      id: uuidv4(),
      userId: userData[0].id,
      menuItemId: menuData[0].id,
      quantity: 2,
      orderAmount: menuData[0].price * 2,
    },
  ];
  await db.insert(cart).values(cartData);

  const orderData = [
    {
      id: 1,
      userId: userData[0].id,
      deliveryAddressId: addressData[0].id,
      restaurantId: restaurantData[0].id,
      cartId: cartData[0].id,
      courierId: courierData[0].id,
      statusId: statusData[0].id,
      paymentMethodId: paymentMethodsData[0].id,
      orderDate: new Date().toISOString(),
    },
    {
      id: 2,
      userId: userData[0].id,
      deliveryAddressId: addressData[0].id,
      restaurantId: restaurantData[1].id,
      cartId: cartData[0].id,
      courierId: courierData[0].id,
      statusId: statusData[0].id,
      paymentMethodId: paymentMethodsData[0].id,
      orderDate: new Date().toISOString(),
    },
    {
      id: 3,
      userId: userData[0].id,
      deliveryAddressId: addressData[0].id,
      restaurantId: restaurantData[0].id,
      cartId: cartData[0].id,
      courierId: courierData[0].id,
      statusId: statusData[0].id,
      paymentMethodId: paymentMethodsData[0].id,
      orderDate: new Date().toISOString(),
    },
    {
      id: 4,
      userId: userData[0].id,
      deliveryAddressId: addressData[0].id,
      restaurantId: restaurantData[1].id,
      cartId: cartData[0].id,
      courierId: courierData[0].id,
      statusId: statusData[0].id,
      paymentMethodId: paymentMethodsData[0].id,
      orderDate: new Date().toISOString(),
    },
  ];
  await db.insert(orders).values(orderData);

  console.log('✅ База данных успешно заполнена!');
}

seed()
  .then(() => process.exit(0))
  .catch(error => {
    console.error('❌ Ошибка при заполнении базы:', error);
    process.exit(1);
  });
