import { v4 as uuidv4 } from 'uuid';

import { db } from './index';
import {
  cart,
  categories,
  couriers,
  deliveryAddresses,
  favorites,
  menuItems,
  orders,
  orderStatuses,
  paymentMethods,
  restaurants,
  users,
} from './schema';

async function seed() {
  console.log('🌱 Заполнение базы данных...');

  // Очистка таблиц перед заполнением
  await db.delete(restaurants);
  await db.delete(menuItems);
  await db.delete(categories);
  await db.delete(cart);
  await db.delete(favorites);
  await db.delete(orders);
  await db.delete(deliveryAddresses);
  await db.delete(paymentMethods);
  await db.delete(users);
  await db.delete(orderStatuses);
  await db.delete(couriers);

  const restaurantData = [
    {
      id: uuidv4(),
      name: 'Трапеза Ярополка',
      description: 'Традиционная кухня',
      rating: 5,
      deliveryTime: '30-40 мин',
      cuisineType: 'Славянская',
      averagePrice: 1500,
      imageUrl: '/images/restaurants/yaropolk.png',
    },
    {
      id: uuidv4(),
      name: 'Мед и перец',
      description: 'Современные блюда с акцентом на местные продукты',
      rating: 4,
      deliveryTime: '40-50 мин',
      cuisineType: 'Европейская',
      averagePrice: 2000,
      imageUrl: '/images/restaurants/honey-pepper.png',
    },
    {
      id: uuidv4(),
      name: '«Славянский пир»',
      description: 'Аутентичные рецепты, блюда для гурманов',
      rating: 3,
      deliveryTime: '25-35 мин',
      cuisineType: 'Микс кулинарных традиций',
      averagePrice: 1200,
      imageUrl: '/images/restaurants/slavic-party.png',
    },
    {
      id: uuidv4(),
      name: 'Берестяной двор',
      description: 'Блюда в старинном стиле, традиционные супы и пироги',
      rating: 4.7,
      deliveryTime: '25-35 мин',
      cuisineType: 'Традиционная русская',
      averagePrice: 1000,
      imageUrl: '/images/restaurants/beresta.png',
    },
    {
      id: uuidv4(),
      name: 'Варган',
      description: 'Специи и ароматы севера и юга',
      rating: 4.2,
      deliveryTime: '20-30 мин',
      cuisineType: 'Микс кулинарных традиций',
      averagePrice: 900,
      imageUrl: '/images/restaurants/vargan.png',
    },
    {
      id: uuidv4(),
      name: 'Булочная у Радмилы',
      description: 'Свежая выпечка, пироги и домашние десерты',
      rating: 3.7,
      deliveryTime: '15-25 мин',
      cuisineType: 'Кондитерская',
      averagePrice: 700,
      imageUrl: '/images/restaurants/radmila.png',
    },
    {
      id: uuidv4(),
      name: '«Городской дворик»',
      description: 'Уличная еда и сытные закуски',
      rating: 2.7,
      deliveryTime: '20-30 мин',
      cuisineType: 'Стритфуд',
      averagePrice: 1000,
      imageUrl: '/images/restaurants/dvorik.png',
    },
    {
      id: uuidv4(),
      name: 'Лесное застолье',
      description: 'Фермерская кухня, экологически чистые продукты',
      rating: 5,
      deliveryTime: '25-35 мин',
      cuisineType: 'Органическая',
      averagePrice: 1950,
      imageUrl: '/images/restaurants/lesnoe.png',
    },
    {
      id: uuidv4(),
      name: 'Рыбацкая артель',
      description: 'Уникальное сочетание вкусов со всего мира.',
      rating: 4.4,
      deliveryTime: '40-50 мин',
      cuisineType: 'Рыбная',
      averagePrice: 900,
      imageUrl: '/images/restaurants/fish.png',
    },
    {
      id: uuidv4(),
      name: 'Таверна "Дворик"',
      description: 'Традиционная кухня',
      rating: 3.1,
      deliveryTime: '43-52 мин',
      cuisineType: 'Французская',
      averagePrice: 2811,
      imageUrl: '/images/restaurants/taverna_dvorik.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гастрономия Мартина',
      description: 'Традиционная кухня',
      rating: 3.4,
      deliveryTime: '45-55 мин',
      cuisineType: 'Средиземноморская',
      averagePrice: 1943,
      imageUrl: '/images/restaurants/gastronomia_martina.jpg',
    },
    {
      id: uuidv4(),
      name: 'Таверна у Маяка',
      description: 'Традиционная кухня',
      rating: 4.7,
      deliveryTime: '47-42 мин',
      cuisineType: 'Азиатская',
      averagePrice: 1044,
      imageUrl: '/images/restaurants/taverna_u_mayaka.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гастрономическая площадь',
      description: 'Современная кухня',
      rating: 2.8,
      deliveryTime: '41-32 мин',
      cuisineType: 'Американская',
      averagePrice: 2151,
      imageUrl: '/images/restaurants/gastronomicheskaya_ploshad.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Бар "Шеф"',
      description: 'Современная кухня',
      rating: 2.6,
      deliveryTime: '46-49 мин',
      cuisineType: 'Средиземноморская',
      averagePrice: 2326,
      imageUrl: '/images/restaurants/grill_bar_shef.jpg',
    },
    {
      id: uuidv4(),
      name: 'Грильхаус "Восток"',
      description: 'Современная кухня',
      rating: 2.0,
      deliveryTime: '33-40 мин',
      cuisineType: 'Азиатская',
      averagePrice: 1342,
      imageUrl: '/images/restaurants/grillhaus_vostok.jpg',
    },
    {
      id: uuidv4(),
      name: 'Шторм на Неве',
      description: 'Восточная кухня',
      rating: 2.8,
      deliveryTime: '52-32 мин',
      cuisineType: 'Средиземноморская',
      averagePrice: 1133,
      imageUrl: '/images/restaurants/shtorm_na_neve.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Берег',
      description: 'Современная кухня',
      rating: 4.5,
      deliveryTime: '39-45 мин',
      cuisineType: 'Французская',
      averagePrice: 1800,
      imageUrl: '/images/restaurants/grill_bereg.jpg',
    },
    {
      id: uuidv4(),
      name: 'Шторм в Балтике',
      description: 'Семейное кафе.',
      rating: 1.7,
      deliveryTime: '35-60 мин',
      cuisineType: 'Американская',
      averagePrice: 1900,
      imageUrl: '/images/restaurants/shtorm_v_baltike.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Кафе "На Неве"',
      description: 'Современная кухня',
      rating: 3.9,
      deliveryTime: '28-50 мин',
      cuisineType: 'Кавказская',
      averagePrice: 2555,
      imageUrl: '/images/restaurants/grill_kafe_na_neve.jpg',
    },
    {
      id: uuidv4(),
      name: 'Таверна у Бухты',
      description: 'Традиционная кухня',
      rating: 4.1,
      deliveryTime: '30-45 мин',
      cuisineType: 'Русская',
      averagePrice: 1600,
      imageUrl: '/images/restaurants/taverna_u_buhty.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Кафе "Скала"',
      description: 'Современная кухня',
      rating: 4.2,
      deliveryTime: '28-50 мин',
      cuisineType: 'Азиатская',
      averagePrice: 1450,
      imageUrl: '/images/restaurants/grill_kafe_skala.jpg',
    },
    {
      id: uuidv4(),
      name: 'Шторм на Пляже',
      description: 'Современная кухня',
      rating: 2.9,
      deliveryTime: '40-55 мин',
      cuisineType: 'Американская',
      averagePrice: 2100,
      imageUrl: '/images/restaurants/shtorm_na_plyazhe.jpg',
    },
    {
      id: uuidv4(),
      name: 'Греческая Таверна',
      description: 'Современная кухня',
      rating: 3.3,
      deliveryTime: '22-50 мин',
      cuisineType: 'Греческая',
      averagePrice: 2300,
      imageUrl: '/images/restaurants/grecheskaya_taverna.jpg',
    },
    {
      id: uuidv4(),
      name: 'Морская Пена',
      description: 'Семейное кафе.',
      rating: 4.3,
      deliveryTime: '45-50 мин',
      cuisineType: 'Средиземноморская',
      averagePrice: 1850,
      imageUrl: '/images/restaurants/morskaya_pena.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гастрономия "Челси"',
      description: 'Традиционная кухня',
      rating: 2.7,
      deliveryTime: '50-60 мин',
      cuisineType: 'Русская',
      averagePrice: 1450,
      imageUrl: '/images/restaurants/gastronomiya_chelsea.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Парк "Зелёный"',
      description: 'Восточная кухня',
      rating: 3.5,
      deliveryTime: '35-50 мин',
      cuisineType: 'Русская',
      averagePrice: 2300,
      imageUrl: '/images/restaurants/grill_park_zelenyy.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гастрономический Плавник',
      description: 'Семейное кафе.',
      rating: 4.0,
      deliveryTime: '30-45 мин',
      cuisineType: 'Средиземноморская',
      averagePrice: 2100,
      imageUrl: '/images/restaurants/gastronomicheskiy_plavnik.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Кафе на Лагуне',
      description: 'Современная кухня',
      rating: 3.9,
      deliveryTime: '30-50 мин',
      cuisineType: 'Французская',
      averagePrice: 2200,
      imageUrl: '/images/restaurants/grill_kafe_na_lagune.jpg',
    },
    {
      id: uuidv4(),
      name: 'Фестиваль Вкусов',
      description: 'Гастрономический эксперимент с уникальными блюдами',
      rating: 4.8,
      deliveryTime: '35-45 мин',
      cuisineType: 'Фьюжн',
      averagePrice: 1800,
      imageUrl: '/images/restaurants/festival_vkusov.jpg',
    },
    {
      id: uuidv4(),
      name: 'Бруклинский Вкус',
      description: 'Американская кухня с новыми акцентами',
      rating: 4.2,
      deliveryTime: '30-40 мин',
      cuisineType: 'Американская',
      averagePrice: 1600,
      imageUrl: '/images/restaurants/bruklinskiy_vkus.jpg',
    },
    {
      id: uuidv4(),
      name: 'Тайский Лотос',
      description: 'Острая и ароматная кухня Таиланда',
      rating: 4.5,
      deliveryTime: '25-35 мин',
      cuisineType: 'Тайская',
      averagePrice: 1300,
      imageUrl: '/images/restaurants/thayskiy_lotos.jpg',
    },
    {
      id: uuidv4(),
      name: 'Пекарня Лавка',
      description: 'Домашний хлеб, пироги и выпечка',
      rating: 3.9,
      deliveryTime: '20-30 мин',
      cuisineType: 'Пекарня',
      averagePrice: 500,
      imageUrl: '/images/restaurants/pekarnya_lavka.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Академия',
      description: 'Лучший гриль в городе',
      rating: 4.1,
      deliveryTime: '40-50 мин',
      cuisineType: 'Гриль',
      averagePrice: 2200,
      imageUrl: '/images/restaurants/grill_akademiya.jpg',
    },
    {
      id: uuidv4(),
      name: 'Санкт-Петербургский Пирог',
      description: 'Русская выпечка и традиционные блюда',
      rating: 4.3,
      deliveryTime: '30-40 мин',
      cuisineType: 'Русская',
      averagePrice: 1200,
      imageUrl: '/images/restaurants/sant_peterburgskiy_pirog.jpg',
    },
    {
      id: uuidv4(),
      name: 'Мексиканская Буря',
      description: 'Острые блюда и коктейли по мексиканским рецептам',
      rating: 4.0,
      deliveryTime: '25-35 мин',
      cuisineType: 'Мексиканская',
      averagePrice: 1500,
      imageUrl: '/images/restaurants/meksikanskaya_burya.jpg',
    },
    {
      id: uuidv4(),
      name: 'Лавка Кофе',
      description: 'Лучший кофе и десерты с акцентом на классику',
      rating: 4.4,
      deliveryTime: '15-20 мин',
      cuisineType: 'Кофейня',
      averagePrice: 700,
      imageUrl: '/images/restaurants/lavka_kofe.jpg',
    },
    {
      id: uuidv4(),
      name: 'Суши Гурмэ',
      description: 'Свежие суши и сашими по классическим рецептам',
      rating: 5.0,
      deliveryTime: '30-40 мин',
      cuisineType: 'Японская',
      averagePrice: 1700,
      imageUrl: '/images/restaurants/sushi_gurme.jpg',
    },
    {
      id: uuidv4(),
      name: 'Ресторан "Токио"',
      description: 'Уникальное сочетание традиционной японской и современной кухни',
      rating: 4.6,
      deliveryTime: '20-30 мин',
      cuisineType: 'Японская',
      averagePrice: 2100,
      imageUrl: '/images/restaurants/restoran_tokyo.jpg',
    },
    {
      id: uuidv4(),
      name: 'Кулинарная Мастерская',
      description: 'Традиционная кухня с инновационными подходами',
      rating: 4.0,
      deliveryTime: '25-35 мин',
      cuisineType: 'Европейская',
      averagePrice: 1500,
      imageUrl: '/images/restaurants/kulinarnaya_masterskaya.jpg',
    },
    {
      id: uuidv4(),
      name: 'Палитра Вкусов',
      description: 'Блюда со всего мира, от классики до фьюжн',
      rating: 3.9,
      deliveryTime: '35-45 мин',
      cuisineType: 'Международная',
      averagePrice: 1600,
      imageUrl: '/images/restaurants/palitra_vkusov.jpg',
    },
    {
      id: uuidv4(),
      name: 'Бельгийский Кафе',
      description: 'Бельгийские вафли и пиво',
      rating: 4.3,
      deliveryTime: '25-30 мин',
      cuisineType: 'Бельгийская',
      averagePrice: 1800,
      imageUrl: '/images/restaurants/belgijskiy_kafe.jpg',
    },
    {
      id: uuidv4(),
      name: 'Паназиатская Кухня',
      description: 'Азия на вашем столе, от Японии до Индии',
      rating: 4.7,
      deliveryTime: '40-50 мин',
      cuisineType: 'Азиатская',
      averagePrice: 2000,
      imageUrl: '/images/restaurants/panaziatskaya_kuhnya.jpg',
    },
    {
      id: uuidv4(),
      name: 'Пивной Пирог',
      description: 'Сытная еда и широкий выбор пива',
      rating: 3.8,
      deliveryTime: '30-40 мин',
      cuisineType: 'Пивной бар',
      averagePrice: 1300,
      imageUrl: '/images/restaurants/pivnoy_pirog.jpg',
    },
    {
      id: uuidv4(),
      name: 'Легенды Средиземноморья',
      description: 'Традиционные блюда с юга Европы',
      rating: 4.5,
      deliveryTime: '35-45 мин',
      cuisineType: 'Средиземноморская',
      averagePrice: 2200,
      imageUrl: '/images/restaurants/legendy_sredizemnomorya.jpg',
    },
    {
      id: uuidv4(),
      name: 'Гриль-Палата',
      description: 'Лучший гриль-бар в городе с атмосферой уюта',
      rating: 4.2,
      deliveryTime: '40-50 мин',
      cuisineType: 'Гриль',
      averagePrice: 1800,
      imageUrl: '/images/restaurants/grill_palata.jpg',
    },
    {
      id: uuidv4(),
      name: 'Мираторг',
      description: 'Стейкхаус с фокусом на мясо высшего качества',
      rating: 4.3,
      deliveryTime: '30-40 мин',
      cuisineType: 'Стейкхаус',
      averagePrice: 2500,
      imageUrl: '/images/restaurants/miratorg.jpg',
    },
    {
      id: uuidv4(),
      name: 'Техасская Ранчо',
      description: 'Настоящее техасское барбекю и мясные блюда',
      rating: 4.6,
      deliveryTime: '45-55 мин',
      cuisineType: 'Американская',
      averagePrice: 2200,
      imageUrl: '/images/restaurants/texasskaya_rancho.jpg',
    },
    {
      id: uuidv4(),
      name: 'Морской Ветер',
      description: 'Рыбные блюда и морепродукты по особым рецептам',
      rating: 5.0,
      deliveryTime: '25-35 мин',
      cuisineType: 'Рыбная',
      averagePrice: 2000,
      imageUrl: '/images/restaurants/morskoj_veter.jpg',
    },
    {
      id: uuidv4(),
      name: 'Веганский Рай',
      description: 'Кухня для веганов и вегетарианцев, богатая витаминами и вкусами',
      rating: 4.7,
      deliveryTime: '30-40 мин',
      cuisineType: 'Веганская',
      averagePrice: 1400,
      imageUrl: '/images/restaurants/veganskiy_rai.jpg',
    },
    {
      id: uuidv4(),
      name: 'Итальянский Вкус',
      description: 'Традиционная итальянская кухня с акцентом на пасту и пиццу',
      rating: 4.6,
      deliveryTime: '35-45 мин',
      cuisineType: 'Итальянская',
      averagePrice: 1800,
      imageUrl: '/images/restaurants/italyanskiy_vkus.jpg',
    },
  ];
  await db.insert(restaurants).values(restaurantData);

  const categoryData = [
    { id: uuidv4(), restaurantId: restaurantData[0].id, name: 'Основные блюда' },
    { id: uuidv4(), restaurantId: restaurantData[1].id, name: 'Основные блюда' },
    { id: uuidv4(), restaurantId: restaurantData[0].id, name: 'Десерты' },
    { id: uuidv4(), restaurantId: restaurantData[1].id, name: 'Десерты' },
  ];
  await db.insert(categories).values(categoryData);

  const menuData = [
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[0].id,
      name: 'Филе миньон',
      description: 'Нежнейшая говядина с соусом.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[1].id,
      name: 'Филе миньон 2',
      description: 'Нежнейшая говядина с соусом.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[0].id,
      name: 'Филе миньон 3',
      description: 'Нежнейшая говядина с соусом.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[3].id,
      restaurantId: restaurantData[1].id,
      name: 'Филе миньон 4',
      description: 'Нежнейшая говядина с соусом.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[2].id,
      restaurantId: restaurantData[0].id,
      name: 'Филе миньон 5',
      description: 'Нежнейшая говядина с соусом.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[0].id,
      restaurantId: restaurantData[0].id,
      name: 'Филе миньон 6',
      description: 'Нежнейшая говядина с соусом.',
      price: 1500,
      imageUrl: '/images/food.png',
    },
    {
      id: uuidv4(),
      categoryId: categoryData[1].id,
      restaurantId: restaurantData[1].id,
      name: 'Чизкейк',
      description: 'Классический чизкейк с ягодами.',
      price: 600,
      imageUrl: '/images/food.png',
    },
  ];
  await db.insert(menuItems).values(menuData);

  const userData = [
    {
      id: uuidv4(),
      firstName: 'Иван',
      lastName: 'Иванов',
      accountName: 'ivan123',
      email: 'ivan@example.com',
      passwordHash: 'hashedpassword',
      phone: '79990001122',
      address: 'Москва',
      cardNumber: '1234123412341234',
    },
  ];
  await db.insert(users).values(userData);

  const addressData = [
    { id: 1, userId: userData[0].id, address: 'Ленина, 10', comment: 'code: 1111' },
  ];
  await db.insert(deliveryAddresses).values(addressData);

  const paymentMethodsData = [
    { id: 1, userId: userData[0].id, type: 'Карта', details: '1234 4321 4321 1234' },
  ];
  await db.insert(paymentMethods).values(paymentMethodsData);

  const statusData = [
    { id: 1, name: 'Создан' },
    { id: 2, name: 'В пути' },
    { id: 3, name: 'Доставлен' },
  ];
  await db.insert(orderStatuses).values(statusData);

  const courierData = [{ id: 1, name: 'Сергей', phone: '79991234567' }];
  await db.insert(couriers).values(courierData);

  const cartData = [
    {
      id: uuidv4(),
      userId: userData[0].id,
      menuItemId: menuData[0].id,
      quantity: 2,
      orderAmount: menuData[0].price * 2,
    },
  ];
  await db.insert(cart).values(cartData);

  const orderData = [
    {
      id: 1,
      userId: userData[0].id,
      deliveryAddressId: addressData[0].id,
      restaurantId: restaurantData[0].id,
      cartId: cartData[0].id,
      courierId: courierData[0].id,
      statusId: statusData[0].id,
      paymentMethodId: paymentMethodsData[0].id,
      orderDate: new Date().toISOString(),
    },
    {
      id: 2,
      userId: userData[0].id,
      deliveryAddressId: addressData[0].id,
      restaurantId: restaurantData[1].id,
      cartId: cartData[0].id,
      courierId: courierData[0].id,
      statusId: statusData[0].id,
      paymentMethodId: paymentMethodsData[0].id,
      orderDate: new Date().toISOString(),
    },
    {
      id: 3,
      userId: userData[0].id,
      deliveryAddressId: addressData[0].id,
      restaurantId: restaurantData[0].id,
      cartId: cartData[0].id,
      courierId: courierData[0].id,
      statusId: statusData[0].id,
      paymentMethodId: paymentMethodsData[0].id,
      orderDate: new Date().toISOString(),
    },
    {
      id: 4,
      userId: userData[0].id,
      deliveryAddressId: addressData[0].id,
      restaurantId: restaurantData[1].id,
      cartId: cartData[0].id,
      courierId: courierData[0].id,
      statusId: statusData[0].id,
      paymentMethodId: paymentMethodsData[0].id,
      orderDate: new Date().toISOString(),
    },
  ];
  await db.insert(orders).values(orderData);

  console.log('✅ База данных успешно заполнена!');
}

seed()
  .then(() => process.exit(0))
  .catch(error => {
    console.error('❌ Ошибка при заполнении базы:', error);
    process.exit(1);
  });
